In [10]:
import numpy as np
rows=int(input("enter no. of rows"))
col=int(input("enetr no. of colums"))
print("enter matrix1 elements")
elements1= list(map(int, input().split()))
matrix1=np.array(elements1).reshape(rows,col)
print("enter matrix2 elements")
elements2=list(map(int, input().split()))
matrix2=np.array(elements2).reshape(rows,col)
print("matrix1 \n",matrix1)
print("matrix2 \n",matrix2)
print("dot product \n",np.dot(matrix1,matrix2))
print("transpose \n",np.transpose(matrix1))
print("trace \n",np.trace(matrix1))
print("rank \n",np.linalg.matrix_rank(matrix1))
print("determinant \n",np.linalg.det(matrix1))
print("inverse \n",np.linalg.inv(matrix1))
w, v = np.linalg.eig(matrix1)
print("\nEigenvalues:")
print(w)
print("\nEigenvectors:")
print(v)

enter no. of rows2
enetr no. of colums2
enter matrix1 elements
2 3 4 5
enter matrix2 elements
5 6 7 8
matrix1 
 [[2 3]
 [4 5]]
matrix2 
 [[5 6]
 [7 8]]
dot product 
 [[31 36]
 [55 64]]
transpose 
 [[2 4]
 [3 5]]
trace 
 7
rank 
 2
determinant 
 -2.0
inverse 
 [[-2.5  1.5]
 [ 2.  -1. ]]

Eigenvalues:
[-0.27491722  7.27491722]

Eigenvectors:
[[-0.79681209 -0.49436913]
 [ 0.60422718 -0.86925207]]
